# Generated by Django 5.2.4 on 2025-07-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekjoon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_day', models.CharField(max_length=30)),
            ],
        ),
    ]
